heat_template_version: 2015-10-15

parameters:
  first_address_list:
    type: json

resources:
  Node_config:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      outputs:
        - name: cluster.crt
        - name: nodes.crt
        - name: nodes.key
      config: |
        #!/bin/bash
        mkdir /etc/flocker
        cd /etc/flocker
        flocker-ca initialize $consul_path
        cat cluster.crt > ${heat_outputs_path}.cluster.crt
        flocker-ca create-control-certificate $local_ip
        mv control-$local_ip.key control-service.key
        mv control-$local_ip.crt control-service.crt
        chmod 0700 /etc/flocker
        chmod 0600 /etc/flocker/control-service.key
        for i in $first_address_list
        do
        flocker-ca create-node-certificate
        cat $(ls -tr *.key | tail -1) >> ${heat_outputs_path}.nodes.key
        cat $(ls -tr *.crt | tail -1) >> ${heat_outputs_path}.nodes.crt
        done
        csplit -szf file ca-certificates.crt /-----END\ CERTIFICATE-----/+1 {*}
  Node_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      input_values:
        first_address_list: {get_param: first_address_list}
      config:
        get_resource: Node_config
      server:
        get_param: server

outputs:

  cluster.crt:
    value:
      get_attr: [Node_deployment, cluster.crt]
  nodes.crt:
    value:
      get_attr: [Node_deployment, nodes.crt]
  nodes.key:
    value:
      get_attr: [Node_deployment, nodes.key]
